name: twinspeak-dev
services:
  whisper:
    profiles: ["whisper"]
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: twinspeak-whisper-dev
    environment:
      - ASR_MODEL=medium
      - ASR_ENGINE=faster_whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - twinspeak-dev

  libretranslate:
    profiles: ["whisper"]
    container_name: twinspeak-libretranslate-dev
    image: libretranslate/libretranslate:latest-cuda
    restart: unless-stopped
    command: --disable-web-ui
    environment:
     - LT_UPDATE_MODELS=True
     - LT_DEBUG=True
     - PUID=root
    volumes:
     - libretranslate:/app/db
     - libretranslate:/root/.local:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    networks:
      - twinspeak-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: twinspeak-backend-dev
    volumes:
      - ./backend:/app
      - /app/tmp
    networks:
      - twinspeak-dev
    command: air -c .air.toml 

  frontend:
    image: node:24-alpine
    container_name: twinspeak-frontend-dev
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - twinspeak-dev
    depends_on:
      - backend
    command: sh -c "corepack enable && corepack prepare pnpm@11.5.2 --activate && pnpm install && pnpm dev --host"

  db:
    image: postgres:18
    container_name: twinspeak-db-dev
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: twinspeak
    networks:
      - twinspeak-dev
    volumes:
      - postgresdatadev:/var/lib/postgresql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: twinspeak-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - twinspeak-dev
    depends_on:
      - frontend
      - backend
    environment:
      - BACKEND_HOST=backend:8080
      - FRONTEND_HOST=frontend:4321
    security_opt:
      - no-new-privileges:true

networks:
  twinspeak-dev:
    driver: bridge

volumes: 
  libretranslate: 
  postgresdatadev:
