host: 0.0.0.0:8080
public-url: http://www.twinspeak.site
db-url: postgresql://postgres:postgres@db:5432/twinspeek
hmac-secret: some_key
pipeline: gladia
gladia-key: some_key
faster-whisper-url: http://whisper:9000
libretranslate-url: http://libretranslate:5000
google:
  client-id: client_id
  client-secret: client_secret
  redirect-url: https://redirect_url
resend:
  api-key: some_key
  from-email: noreply@contact.twinspeak.site
