// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type RefreshSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	UserAgent *string
	Ip        *netip.Addr
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   []byte
	EmailVerified  bool
	ProfilePicture *string
	GoogleSub      *string
	CreatedAt      time.Time
}
