// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAccountFromGoogle = `-- name: CreateAccountFromGoogle :one
insert into users (
    google_sub, email, email_verified, profile_picture
) values (
    $1, $2, true, $3
)
returning id
`

type CreateAccountFromGoogleParams struct {
	GoogleSub      *string
	Email          string
	ProfilePicture *string
}

func (q *Queries) CreateAccountFromGoogle(ctx context.Context, arg CreateAccountFromGoogleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccountFromGoogle, arg.GoogleSub, arg.Email, arg.ProfilePicture)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
insert into refresh_sessions (
    user_id, token_hash, user_agent, ip, expires_at
) values (
    $1, $2, $3, $4, $5
)
returning id
`

type CreateRefreshSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	UserAgent *string
	Ip        *netip.Addr
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash) values ($1, $2)
returning id
`

type CreateUserParams struct {
	Email        string
	PasswordHash []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findAccountFromGoogle = `-- name: FindAccountFromGoogle :one
select id from users where google_sub = $1
`

func (q *Queries) FindAccountFromGoogle(ctx context.Context, googleSub *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findAccountFromGoogle, googleSub)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRefreshSessionForUpdate = `-- name: GetRefreshSessionForUpdate :one
select id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at from refresh_sessions where token_hash = $1 for update
`

func (q *Queries) GetRefreshSessionForUpdate(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionForUpdate, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, email_verified, profile_picture, google_sub, created_at from users where email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfilePicture,
		&i.GoogleSub,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :exec
update refresh_sessions set revoked_at = now() where token_hash = $1
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshSession, tokenHash)
	return err
}
