/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteRouteImport } from './routes/verify-email/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as VerifyEmailCallbackRouteImport } from './routes/verify-email/callback'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google-callback'

const VerifyEmailRouteRoute = VerifyEmailRouteRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifyEmailRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailCallbackRoute = VerifyEmailCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => VerifyEmailRouteRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google-callback',
  path: '/auth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/verify-email': typeof VerifyEmailRouteRouteWithChildren
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/verify-email/callback': typeof VerifyEmailCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/verify-email/callback': typeof VerifyEmailCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/verify-email': typeof VerifyEmailRouteRouteWithChildren
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/verify-email/callback': typeof VerifyEmailCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/verify-email'
    | '/auth/google-callback'
    | '/auth/recovery'
    | '/settings/account'
    | '/settings/preferences'
    | '/verify-email/callback'
    | '/auth/'
    | '/settings/'
    | '/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/google-callback'
    | '/auth/recovery'
    | '/settings/account'
    | '/settings/preferences'
    | '/verify-email/callback'
    | '/auth'
    | '/settings'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/verify-email'
    | '/auth/google-callback'
    | '/auth/recovery'
    | '/settings/account'
    | '/settings/preferences'
    | '/verify-email/callback'
    | '/auth/'
    | '/settings/'
    | '/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  VerifyEmailRouteRoute: typeof VerifyEmailRouteRouteWithChildren
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof VerifyEmailRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/callback': {
      id: '/verify-email/callback'
      path: '/callback'
      fullPath: '/verify-email/callback'
      preLoaderRoute: typeof VerifyEmailCallbackRouteImport
      parentRoute: typeof VerifyEmailRouteRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google-callback': {
      id: '/auth/google-callback'
      path: '/auth/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface VerifyEmailRouteRouteChildren {
  VerifyEmailCallbackRoute: typeof VerifyEmailCallbackRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

const VerifyEmailRouteRouteChildren: VerifyEmailRouteRouteChildren = {
  VerifyEmailCallbackRoute: VerifyEmailCallbackRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}

const VerifyEmailRouteRouteWithChildren =
  VerifyEmailRouteRoute._addFileChildren(VerifyEmailRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  VerifyEmailRouteRoute: VerifyEmailRouteRouteWithChildren,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
