// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAccountFromGoogle = `-- name: CreateAccountFromGoogle :one
insert into users (
    google_sub, email, email_verified, profile_picture
) values (
    $1, $2, true, $3
)
returning id
`

type CreateAccountFromGoogleParams struct {
	GoogleSub      *string
	Email          string
	ProfilePicture *string
}

func (q *Queries) CreateAccountFromGoogle(ctx context.Context, arg CreateAccountFromGoogleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccountFromGoogle, arg.GoogleSub, arg.Email, arg.ProfilePicture)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createCreditExpenses = `-- name: CreateCreditExpenses :exec
insert into credit_expenses (
    user_id, grant_id, spent, spent_at
) values (
    $1, $2, $3, $4
)
`

type CreateCreditExpensesParams struct {
	UserID  uuid.UUID
	GrantID uuid.UUID
	Spent   int32
	SpentAt time.Time
}

func (q *Queries) CreateCreditExpenses(ctx context.Context, arg CreateCreditExpensesParams) error {
	_, err := q.db.Exec(ctx, createCreditExpenses,
		arg.UserID,
		arg.GrantID,
		arg.Spent,
		arg.SpentAt,
	)
	return err
}

const createCreditGrant = `-- name: CreateCreditGrant :exec
insert into credit_grants (
    user_id, amount, remaining_amount, type, expires_at
) values (
    $1, $2, $3, $4, $5
)
`

type CreateCreditGrantParams struct {
	UserID          uuid.UUID
	Amount          int32
	RemainingAmount int32
	Type            CreditGrantType
	ExpiresAt       *time.Time
}

func (q *Queries) CreateCreditGrant(ctx context.Context, arg CreateCreditGrantParams) error {
	_, err := q.db.Exec(ctx, createCreditGrant,
		arg.UserID,
		arg.Amount,
		arg.RemainingAmount,
		arg.Type,
		arg.ExpiresAt,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
insert into password_reset_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
insert into refresh_sessions (
    user_id, token_hash, user_agent, ip, expires_at
) values (
    $1, $2, $3, $4, $5
)
returning id
`

type CreateRefreshSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	UserAgent *string
	Ip        *netip.Addr
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSubscription = `-- name: CreateSubscription :one
insert into subscriptions (user_id, next_monthly_grant_at) values ($1, $2)
returning id
`

type CreateSubscriptionParams struct {
	UserID             uuid.UUID
	NextMonthlyGrantAt time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.NextMonthlyGrantAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash) values ($1, $2)
returning id
`

type CreateUserParams struct {
	Email        string
	PasswordHash []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one
insert into email_verification_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id
`

type CreateVerificationTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
delete from password_reset_tokens where expires_at <= now()
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteExpiredVerificationTokens = `-- name: DeleteExpiredVerificationTokens :exec
delete from email_verification_tokens where expires_at <= now()
`

func (q *Queries) DeleteExpiredVerificationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerificationTokens)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
delete from password_reset_tokens where token_hash = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, tokenHash)
	return err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
delete from email_verification_tokens where token_hash = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteVerificationToken, tokenHash)
	return err
}

const findAccountFromGoogle = `-- name: FindAccountFromGoogle :one
select id from users where google_sub = $1
`

func (q *Queries) FindAccountFromGoogle(ctx context.Context, googleSub *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findAccountFromGoogle, googleSub)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findCreditGrantForSpend = `-- name: FindCreditGrantForSpend :one
select id, user_id, amount, remaining_amount, type, expires_at, created_at from credit_grants 
where 
    user_id = $1 and 
    remaining_amount > 0 and
    (expires_at = null or expires_at > $2)
order by expires_at asc nulls last, type asc, id asc
limit 1 for update
`

type FindCreditGrantForSpendParams struct {
	UserID    uuid.UUID
	ExpiresAt *time.Time
}

func (q *Queries) FindCreditGrantForSpend(ctx context.Context, arg FindCreditGrantForSpendParams) (CreditGrant, error) {
	row := q.db.QueryRow(ctx, findCreditGrantForSpend, arg.UserID, arg.ExpiresAt)
	var i CreditGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.RemainingAmount,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExpiredSubscriptions = `-- name: GetExpiredSubscriptions :many
select user_id from subscriptions where next_monthly_grant_at >= $1
`

func (q *Queries) GetExpiredSubscriptions(ctx context.Context, nextMonthlyGrantAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getExpiredSubscriptions, nextMonthlyGrantAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
select id, user_id, token_hash, created_at, expires_at from password_reset_tokens 
where token_hash = $1 and expires_at > now()
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRefreshSession = `-- name: GetRefreshSession :one
select id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at from refresh_sessions where token_hash = $1
`

func (q *Queries) GetRefreshSession(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSession, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshSessionForUpdate = `-- name: GetRefreshSessionForUpdate :one
select id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at from refresh_sessions where token_hash = $1 for update
`

func (q *Queries) GetRefreshSessionForUpdate(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionForUpdate, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSpeeches = `-- name: GetSpeeches :many
select s.id, s.user_id, s.in_lang, s.out_lang, s.transcription, s.translation, s.chat_side, s.started_at, s.ended_at from (
    select s.id, s.user_id, s.in_lang, s.out_lang, s.transcription, s.translation, s.chat_side, s.started_at, s.ended_at from speeches s
    join preferences p on s.user_id = p.user_id
    where s.user_id = $1 
        and (s.started_at >= p.hide_messages_before or p.hide_messages_before is null)
    order by s.started_at desc 
    limit $2
) as s
order by s.started_at asc
`

type GetSpeechesParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetSpeeches(ctx context.Context, arg GetSpeechesParams) ([]Speech, error) {
	rows, err := q.db.Query(ctx, getSpeeches, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Speech
	for rows.Next() {
		var i Speech
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InLang,
			&i.OutLang,
			&i.Transcription,
			&i.Translation,
			&i.ChatSide,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, email_verified, profile_picture, google_sub, created_at from users where email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfilePicture,
		&i.GoogleSub,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, email_verified, profile_picture, google_sub, created_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfilePicture,
		&i.GoogleSub,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, password_hash, email_verified, profile_picture, google_sub, created_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfilePicture,
		&i.GoogleSub,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCreditGrants = `-- name: GetUserCreditGrants :many
select id, user_id, amount, remaining_amount, type, expires_at, created_at from credit_grants
where
    user_id = $1 and
    (expires_at is null or expires_at > $2)
order by type asc, expires_at asc nulls last, id asc
`

type GetUserCreditGrantsParams struct {
	UserID    uuid.UUID
	ExpiresAt *time.Time
}

func (q *Queries) GetUserCreditGrants(ctx context.Context, arg GetUserCreditGrantsParams) ([]CreditGrant, error) {
	rows, err := q.db.Query(ctx, getUserCreditGrants, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditGrant
	for rows.Next() {
		var i CreditGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.RemainingAmount,
			&i.Type,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPrefs = `-- name: GetUserPrefs :one
select id, user_id, chat_message_size, theme, in_lang, out_lang, hide_messages_before, updated_at from preferences where user_id = $1
`

func (q *Queries) GetUserPrefs(ctx context.Context, userID uuid.UUID) (Preference, error) {
	row := q.db.QueryRow(ctx, getUserPrefs, userID)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatMessageSize,
		&i.Theme,
		&i.InLang,
		&i.OutLang,
		&i.HideMessagesBefore,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationToken = `-- name: GetVerificationToken :one
select id, user_id, token_hash, created_at, expires_at from email_verification_tokens 
where token_hash = $1 and expires_at > now()
`

func (q *Queries) GetVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertHttpRequest = `-- name: InsertHttpRequest :exec
insert into http_requests (
    request_id,
    method,
    route,
    path,
    recieved_at,
    duration_ms,
    response_code,
    request_headers_bytes,
    request_body_bytes,
    response_headers_bytes,
    response_body_bytes,
    ip,
    user_agent,
    error
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type InsertHttpRequestParams struct {
	RequestID            uuid.UUID
	Method               string
	Route                string
	Path                 string
	RecievedAt           time.Time
	DurationMs           int32
	ResponseCode         int16
	RequestHeadersBytes  int32
	RequestBodyBytes     int32
	ResponseHeadersBytes int32
	ResponseBodyBytes    int32
	Ip                   netip.Addr
	UserAgent            *string
	Error                *string
}

func (q *Queries) InsertHttpRequest(ctx context.Context, arg InsertHttpRequestParams) error {
	_, err := q.db.Exec(ctx, insertHttpRequest,
		arg.RequestID,
		arg.Method,
		arg.Route,
		arg.Path,
		arg.RecievedAt,
		arg.DurationMs,
		arg.ResponseCode,
		arg.RequestHeadersBytes,
		arg.RequestBodyBytes,
		arg.ResponseHeadersBytes,
		arg.ResponseBodyBytes,
		arg.Ip,
		arg.UserAgent,
		arg.Error,
	)
	return err
}

const insertSpeech = `-- name: InsertSpeech :exec
insert into speeches (
    user_id, in_lang, out_lang, transcription, translation, chat_side, started_at, ended_at
) values (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertSpeechParams struct {
	UserID        uuid.UUID
	InLang        string
	OutLang       string
	Transcription string
	Translation   string
	ChatSide      ChatSide
	StartedAt     time.Time
	EndedAt       time.Time
}

func (q *Queries) InsertSpeech(ctx context.Context, arg InsertSpeechParams) error {
	_, err := q.db.Exec(ctx, insertSpeech,
		arg.UserID,
		arg.InLang,
		arg.OutLang,
		arg.Transcription,
		arg.Translation,
		arg.ChatSide,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const insertUserPrefs = `-- name: InsertUserPrefs :exec
insert into preferences(user_id) values ($1)
`

func (q *Queries) InsertUserPrefs(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertUserPrefs, userID)
	return err
}

const linkAccountToGoogle = `-- name: LinkAccountToGoogle :one
update users set 
    profile_picture = $1, 
    google_sub = $2,
    email_verified = true
where email = $3
returning id
`

type LinkAccountToGoogleParams struct {
	ProfilePicture *string
	GoogleSub      *string
	Email          string
}

func (q *Queries) LinkAccountToGoogle(ctx context.Context, arg LinkAccountToGoogleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, linkAccountToGoogle, arg.ProfilePicture, arg.GoogleSub, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :exec
update refresh_sessions set revoked_at = now() where token_hash = $1
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshSession, tokenHash)
	return err
}

const setHideMessagesTimestamp = `-- name: SetHideMessagesTimestamp :exec
update preferences
set hide_messages_before = $2
where user_id = $1
`

type SetHideMessagesTimestampParams struct {
	UserID             uuid.UUID
	HideMessagesBefore *time.Time
}

func (q *Queries) SetHideMessagesTimestamp(ctx context.Context, arg SetHideMessagesTimestampParams) error {
	_, err := q.db.Exec(ctx, setHideMessagesTimestamp, arg.UserID, arg.HideMessagesBefore)
	return err
}

const updateGrant = `-- name: UpdateGrant :exec
update credit_grants
set remaining_amount = $2
where id = $1
`

type UpdateGrantParams struct {
	ID              uuid.UUID
	RemainingAmount int32
}

func (q *Queries) UpdateGrant(ctx context.Context, arg UpdateGrantParams) error {
	_, err := q.db.Exec(ctx, updateGrant, arg.ID, arg.RemainingAmount)
	return err
}

const updateSubscription = `-- name: UpdateSubscription :exec
update subscriptions
set next_monthly_grant_at = $2
where user_id = $1
`

type UpdateSubscriptionParams struct {
	UserID             uuid.UUID
	NextMonthlyGrantAt time.Time
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription, arg.UserID, arg.NextMonthlyGrantAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
update users set password_hash = $2 where id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash []byte
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPrefs = `-- name: UpdateUserPrefs :exec
update preferences
set 
    chat_message_size = $2,
    theme = $3,
    in_lang = $4,
    out_lang = $5,
    updated_at = now()
where user_id = $1
`

type UpdateUserPrefsParams struct {
	UserID          uuid.UUID
	ChatMessageSize Size
	Theme           Theme
	InLang          string
	OutLang         string
}

func (q *Queries) UpdateUserPrefs(ctx context.Context, arg UpdateUserPrefsParams) error {
	_, err := q.db.Exec(ctx, updateUserPrefs,
		arg.UserID,
		arg.ChatMessageSize,
		arg.Theme,
		arg.InLang,
		arg.OutLang,
	)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
update users set email_verified = true where id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
