// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAccountFromGoogle = `-- name: CreateAccountFromGoogle :one
insert into users (
    google_sub, email, email_verified, profile_picture
) values (
    $1, $2, true, $3
)
returning id
`

type CreateAccountFromGoogleParams struct {
	GoogleSub      *string
	Email          string
	ProfilePicture *string
}

func (q *Queries) CreateAccountFromGoogle(ctx context.Context, arg CreateAccountFromGoogleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccountFromGoogle, arg.GoogleSub, arg.Email, arg.ProfilePicture)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createCreditExpenses = `-- name: CreateCreditExpenses :exec
insert into credit_expenses (
    user_id, grant_id, spent, spent_at
) values (
    $1, $2, $3, $4
)
`

type CreateCreditExpensesParams struct {
	UserID  uuid.UUID
	GrantID uuid.UUID
	Spent   int32
	SpentAt time.Time
}

func (q *Queries) CreateCreditExpenses(ctx context.Context, arg CreateCreditExpensesParams) error {
	_, err := q.db.Exec(ctx, createCreditExpenses,
		arg.UserID,
		arg.GrantID,
		arg.Spent,
		arg.SpentAt,
	)
	return err
}

const createCreditGrant = `-- name: CreateCreditGrant :exec
insert into credit_grants (
    user_id, amount, remaining_amount, type, expires_at
) values (
    $1, $2, $3, $4, $5
)
`

type CreateCreditGrantParams struct {
	UserID          uuid.UUID
	Amount          int32
	RemainingAmount int32
	Type            CreditGrantType
	ExpiresAt       *time.Time
}

func (q *Queries) CreateCreditGrant(ctx context.Context, arg CreateCreditGrantParams) error {
	_, err := q.db.Exec(ctx, createCreditGrant,
		arg.UserID,
		arg.Amount,
		arg.RemainingAmount,
		arg.Type,
		arg.ExpiresAt,
	)
	return err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
insert into refresh_sessions (
    user_id, token_hash, user_agent, ip, expires_at
) values (
    $1, $2, $3, $4, $5
)
returning id
`

type CreateRefreshSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	UserAgent *string
	Ip        *netip.Addr
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSubscription = `-- name: CreateSubscription :one
insert into subscriptions (user_id, next_monthly_grant_at) values ($1, $2)
returning id
`

type CreateSubscriptionParams struct {
	UserID             uuid.UUID
	NextMonthlyGrantAt time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.NextMonthlyGrantAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash) values ($1, $2)
returning id
`

type CreateUserParams struct {
	Email        string
	PasswordHash []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findAccountFromGoogle = `-- name: FindAccountFromGoogle :one
select id from users where google_sub = $1
`

func (q *Queries) FindAccountFromGoogle(ctx context.Context, googleSub *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findAccountFromGoogle, googleSub)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findCreditGrantForSpend = `-- name: FindCreditGrantForSpend :one
select id, user_id, amount, remaining_amount, type, expires_at, created_at from credit_grants 
where 
    user_id = $1 and 
    remaining_amount > 0 and
    (expires_at = null or expires_at > $2)
order by expires_at asc nulls last
limit 1 for update
`

type FindCreditGrantForSpendParams struct {
	UserID    uuid.UUID
	ExpiresAt *time.Time
}

func (q *Queries) FindCreditGrantForSpend(ctx context.Context, arg FindCreditGrantForSpendParams) (CreditGrant, error) {
	row := q.db.QueryRow(ctx, findCreditGrantForSpend, arg.UserID, arg.ExpiresAt)
	var i CreditGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.RemainingAmount,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExpiredSubscriptions = `-- name: GetExpiredSubscriptions :many
select user_id from subscriptions where next_monthly_grant_at >= $1
`

func (q *Queries) GetExpiredSubscriptions(ctx context.Context, nextMonthlyGrantAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getExpiredSubscriptions, nextMonthlyGrantAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshSession = `-- name: GetRefreshSession :one
select id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at from refresh_sessions where token_hash = $1
`

func (q *Queries) GetRefreshSession(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSession, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshSessionForUpdate = `-- name: GetRefreshSessionForUpdate :one
select id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at from refresh_sessions where token_hash = $1 for update
`

func (q *Queries) GetRefreshSessionForUpdate(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionForUpdate, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, email_verified, profile_picture, google_sub, created_at from users where email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfilePicture,
		&i.GoogleSub,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, password_hash, email_verified, profile_picture, google_sub, created_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfilePicture,
		&i.GoogleSub,
		&i.CreatedAt,
	)
	return i, err
}

const insertHttpRequest = `-- name: InsertHttpRequest :exec
insert into http_requests (
    request_id,
    method,
    route,
    path,
    recieved_at,
    duration_ms,
    response_code,
    request_headers_bytes,
    request_body_bytes,
    response_headers_bytes,
    response_body_bytes,
    ip,
    user_agent,
    error
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type InsertHttpRequestParams struct {
	RequestID            uuid.UUID
	Method               string
	Route                string
	Path                 string
	RecievedAt           time.Time
	DurationMs           int32
	ResponseCode         int16
	RequestHeadersBytes  int32
	RequestBodyBytes     int32
	ResponseHeadersBytes int32
	ResponseBodyBytes    int32
	Ip                   netip.Addr
	UserAgent            *string
	Error                *string
}

func (q *Queries) InsertHttpRequest(ctx context.Context, arg InsertHttpRequestParams) error {
	_, err := q.db.Exec(ctx, insertHttpRequest,
		arg.RequestID,
		arg.Method,
		arg.Route,
		arg.Path,
		arg.RecievedAt,
		arg.DurationMs,
		arg.ResponseCode,
		arg.RequestHeadersBytes,
		arg.RequestBodyBytes,
		arg.ResponseHeadersBytes,
		arg.ResponseBodyBytes,
		arg.Ip,
		arg.UserAgent,
		arg.Error,
	)
	return err
}

const insertSpeech = `-- name: InsertSpeech :exec
insert into speeches (
    user_id, in_lang, out_lang, started_at, ended_at
) values (
    $1, $2, $3, $4, $5
)
`

type InsertSpeechParams struct {
	UserID    uuid.UUID
	InLang    string
	OutLang   string
	StartedAt time.Time
	EndedAt   time.Time
}

func (q *Queries) InsertSpeech(ctx context.Context, arg InsertSpeechParams) error {
	_, err := q.db.Exec(ctx, insertSpeech,
		arg.UserID,
		arg.InLang,
		arg.OutLang,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :exec
update refresh_sessions set revoked_at = now() where token_hash = $1
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshSession, tokenHash)
	return err
}

const updateGrant = `-- name: UpdateGrant :exec
update credit_grants 
set remaining_amount = $2
where id = $1
`

type UpdateGrantParams struct {
	ID              uuid.UUID
	RemainingAmount int32
}

func (q *Queries) UpdateGrant(ctx context.Context, arg UpdateGrantParams) error {
	_, err := q.db.Exec(ctx, updateGrant, arg.ID, arg.RemainingAmount)
	return err
}

const updateSubscription = `-- name: UpdateSubscription :exec
update subscriptions
set next_monthly_grant_at = $2
where user_id = $1
`

type UpdateSubscriptionParams struct {
	UserID             uuid.UUID
	NextMonthlyGrantAt time.Time
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription, arg.UserID, arg.NextMonthlyGrantAt)
	return err
}
